name: yapi

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/yapi.yml'
    branches:
      - master
      - main
jobs:
  yapi:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          load: false
          tags: yapi
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=yapi.tar
      - name: Save
        uses: actions/upload-artifact@v3
        with:
          name: yapi.tar
          path: yapi.tar
          if-no-files-found: error
